### ISSUE TITLE
BobLinux hangs up if the tags in the .tid file are not in alphabetical order

### ISSUE THREAD

**Issue by lacikawiz** [OokTech/TW5-Bob#100]
I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [ ] Windows
- [ ] OSX
- [x] Linux
- [ ] Other

and using

- [ ] The nodejs version
- [x] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [x] I am using the newest version  (TiddlyWiki version 5.1.21 with Bob version 1.2.4)
- [x] The answer to my question isn't listed in the documentation or this isn't
  a question
- [x] This is not a duplicate issue
- [x] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

----
After working some hours on a tiddler, I found that it did not get saved beyond the first version. Upon investigating further, I found that if a tiddler has more than one tags and the tags are not saved in alphabetical order, then the saving of that tiddler will hang up the whole system. It becomes unresponsive to all requests (websocket, http). It does not produce any error messages but simply hangs up. The only thing that takes it out of this state is to restart the BobLinux executable. 

Any change before the hang-up will get saved - indicating the hang-up happens after the save operation. But there's no indication on the UI that anything went wrong and it look like that the Wiki works, except nothing after this point gets saved. 

I attached here a very small tiddler that exhibits that behavior. To test it:
- Add that tiddler to your `tiddlers` directory
- Open the tiddler, make any small changes and then save it
- After that try to re-load the page, it will hang. Also if you look at the websocket connection it will stop responding.

Another tiddler which exhibits this behavior can be easily created by starting a new one, and adding 3 tags before saving it.

[Anything.txt](https://github.com/OokTech/TW5-Bob/files/3615427/Anything.txt)

**Comment by lacikawiz** [comment]
Additional data:
Since this issue causing me a lot of problems, I went back to an earlier version: https://github.com/OokTech/TW5-BobEXE/releases/tag/1.2.2r6 
And that version does not manifest this issue. This might help zero in on the root cause.

**Comment by inmysocks** [comment]
I haven't gotten the behaviour you describe, but I think I see what is causing it.

Details, mostly for me when I get time to fix it:

The tiddlers are now normalised earlier in the saving process, so what happens is that when a .tid file is created and saved on the file system directly the version sent to the browser is already normalised, this includes putting tags in alphabetical order. Then when the browser sends the update back to the server the existing tiddler is not recognised as the same tiddler and a duplicate with the tags put into order is created on the hard drive.

This confusion could be causing an infinite update loop. A solution would be to save the normalised .tid file before sending it to the browser if the normalisation changes the content at all.

**Comment by inmysocks** [comment]
from what I can tell this is now fixed on the dev branch. I am not sure when I will release an updated version of the executables, I would like to get federation worked out for the next release so it may be a little while.

**Comment by lacikawiz** [comment]
Thank you!

The previous version (1.2.2r6) works fine for me. So I will keep using that until the new one comes out. 

Thank you for your work!
