### ISSUE TITLE
simple TW application crushes BobEXE server

### ISSUE THREAD

**Issue by protw** [OokTech/TW5-Bob#103]
I've been using successfully and with great pleasure BobEXE for my wiki farm https://protw.github.io. Actually how the farm works is described in https://protw.github.io/twfarm/.

My configuration:

- OS Windows 10/64bit
- BobExe v. 1.2.4 Mashed Potatoes (TW 5.1.21)

My problem: 

- I try to use a very simple task manager https://kookma.github.io/Shiraz/#shiraz%2Fto-do-list
- After I dragged-and-dropped the code of the task manager into the Node.js environment of BobEXE it works unstable
- The latter means - every time I check an active task as 'done' or vise versa BobEXE server gets crushed and its terminal window is closed
- I checked the very same code using standalone HTML TW - it works fine
- For any case I attach my code, which I adapted a bit for my purposes and native language

I'd be grateful for your assistance in solving this issue.

[shiraz-to-do-list.zip](https://github.com/OokTech/TW5-Bob/files/3658520/shiraz-to-do-list.zip)

**Comment by inmysocks** [comment]
I think that this is caused by a bug introduced in Bob version 1.2.4, it should be fixed in the next version.

**Comment by protw** [comment]
Thanks for response. I'll be waiting...
Olegh Bondarenko
<http://bit.ly/OleghBond>https://bit.ly/oleghbond





пт, 27 вер. 2019 о 13:27 jed <notifications@github.com> пише:

**Comment by protw** [comment]
The issue is solved after the server BobEXE has been updated to version 1.3.0 Tofurkey.

Thanks!
