### ISSUE TITLE
Update 'Using Proxies'  documentation

### ISSUE THREAD

**Issue by KhalfaniWadlington** [OokTech/TW5-Bob#104]
https://github.com/OokTech/TW5-Bob/blob/master/Documentation/Using%20Proxies.tid

The documentation shows an example of caddy server config.
The example does not forward websockets.

```
phone.local:8080 {
  tls /data/data/com.termux/files/home/etc/phone.crt /data/data/com.termux/files/home/etc/phone.key
    proxy /wiki 127.0.0.1:8090 {
    without /wiki
  }
}
```

Here is my caddy server config that forwards websockets and doesn't have tls. 
```
example.com:8081 {
    tls off
    proxy /wiki example.com:8080 {
    websocket 
    without /wiki
    }
```
 
---

I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [ ] Windows
- [ ] OSX
- [ ] Linux
- [X] Other

and using

- [ ] The nodejs version
- [ ] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [ ] I am using the newest version
- [ ] The answer to my question isn't listed in the documentation or this isn't
  a question
- [X] This is not a duplicate issue
- [ ] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

**Comment by inmysocks** [comment]
Thank you, this is added to the documentation for the next version.
