### ISSUE TITLE
Unknown command wsserver - solved

### ISSUE THREAD

**Issue by digitalap3** [OokTech/TW5-Bob#111]
I kept getting this error after following the manual install version on a debian server.  I finally added a slash to BobWiki in the node command and it worked. - "node ./tiddlywiki.js Wikis/BobWiki  --wsserver" did not work but "node ./tiddlywiki.js Wikis/BobWiki/  --wsserver" did.  Hope this saves some others a bit of time.

---

I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [ ] Windows
- [ ] OSX
- [x] Linux
- [ ] Other

and using

- [x] The nodejs version
- [ ] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [x] I am using the newest version
- [x] The answer to my question isn't listed in the documentation or this isn't
  a question
- [x] This is not a duplicate issue
- [x] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

**Comment by inmysocks** [comment]
That is odd. I will experiment a bit but I don't think I have run into this. If I can repeat it I will try and make.sure the.trailing / is optional

**Comment by digitalap3** [comment]
Ok This is embarrassing.  I logged in to duplicate and it didn't make a difference.  I cycled back through my  commands and saw that I was entering BobWiki as Bobwiki. Like 7 times.  And then I spelled it correctly the time I put the trailing / in.  I'll fall back on my usual excuse - I work nights and I rarely even know what day it is.

I apologize for any time wasted.
