### ISSUE TITLE
Launch of BobEXE is not correct

### ISSUE THREAD

**Issue by protw** [OokTech/TW5-Bob#112]
After launching the latest BobEXE 1.3.1 I see in the web-address field of my Chrome browser `undefined:8080` instead of `127.0.0.1:8080`.

---

I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [X] Windows 10
- [ ] OSX
- [ ] Linux
- [ ] Other

and using

- [X] The nodejs version
- [ ] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [X] I am using the newest version - BobEXE 1.3.1
- [X] The answer to my question isn't listed in the documentation or this isn't
  a question
- [X] This is not a duplicate issue
- [ ] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

**Comment by inmysocks** [comment]
Is this with a new instance without any existing wikis or settings?

**Comment by protw** [comment]
No. It is an existing wiki farm. I have just updated `BobWin.exe` (as I actually did several times before). Meanwhile I returned to the last previous version.

**Comment by inmysocks** [comment]
What do you have set as the host value under wsserver in settings.json?

**Comment by protw** [comment]
```
  "ws-server": {
    "port": "8080"
  },
```

**Comment by inmysocks** [comment]
try removing that section of the settings.json and see if it works.

**Comment by protw** [comment]
I've just removed the mentioned above section from `IndexWiki\settings\settings.json`. So far no effect:

![191021-BobEXE-undefined](https://user-images.githubusercontent.com/1643432/67178304-e14f4700-f3da-11e9-8cf5-c58283bbd602.png)

**Comment by protw** [comment]
Though, after I put a proper web-address manually, i.e. `127.0.0.1:8080` it works fine...

**Comment by inmysocks** [comment]
Did putting in the correct address not work before? That is a completely separate thing.

Try replacing the default values for the wsserver section of the settings.
"ws-server": {
    "port": 8080,
    "host": "127.0.0.1",
    "autoIncrementPort": false
  },`

**Comment by inmysocks** [comment]
Is this still a problem in the newest version? If it isn't I am closing the issue.

**Comment by protw** [comment]
Thanks a lot, no problems with the newest version  so far.
Olegh Bondarenko
<http://bit.ly/OleghBond>https://bit.ly/oleghbond





нд, 1 груд. 2019 о 11:09 jed <notifications@github.com> пише:
