### ISSUE TITLE
Cannot add property hash, object is not extensible

### ISSUE THREAD

**Issue by PaulReiber** [OokTech/TW5-Bob#115]
BUG 1)   I noted a bug with internalFetch when resolution='force' - it's not
working at all, and I get the following error on the console:

WebSocket error:  TypeError: Cannot add property hash, object is not extensible

BUGS 2&3) I also emailed inmysocks with details on what I'm seeing from my testing of internalFetch, regarding extra tiddlers getting created in the (a) source wiki (b) main wiki along with the ones which should be getting created in the (c) destination wiki.

If you have any questions don't hesitate to reach out.

---

I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [ ] Windows
- [ ] OSX
- [x] Linux
- [ ] Other

and using

- [ ] The nodejs version
- [x] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [x] I am using the newest version
- [x] The answer to my question isn't listed in the documentation or this isn't
  a question
- [x] This is not a duplicate issue
- [x] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

**Comment by inmysocks** [comment]
These should all be fixed on the dev branch now.

I missed updates in some places when I re-did the server component.

**Comment by inmysocks** [comment]
I believe this is fixed so I am closing the issue. Reopen it or start a new issue if the problem persists.
