### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by lepascalou** [OokTech/TW5-Bob#118]
Hello,

There is a small typo in two files where it reads **plugnis** instead of **plugins**, though it doesn't seem to alter the expected functioning of Bob.
The files are :   

`ControlPanel/CreateWikis.tid:title: $:/plugnis/OokTech/Bob/CreateWikis`

`ControlPanel/ManageWikis.tid:<<tabs "[[$:/plugins/OokTech/Bob/Wiki Listing]][[$:/plugnis/OokTech/Bob/CreateWikis]]`

---
I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [ ] Windows
- [ ] OSX
- [x] Linux
- [ ] Other

and using

- [ ] The nodejs version
- [x] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [x] I am using the newest version
- [x] The answer to my question isn't listed in the documentation or this isn't
  a question
- [x] This is not a duplicate issue
- [x] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

**Comment by inmysocks** [comment]
Thank you for the correction!

I updated the names, the typo will be fixed in the next version.
