### ISSUE TITLE
FileServerSetup doesn't set default filePathRoot, leading to file server errors

### ISSUE THREAD

**Issue by ConorLPBoyle** [OokTech/TW5-Bob#123]
When using the file server, I kept getting the following error when accessing any /files path:

```
internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.resolve (path.js:1080:7)
    at Object.exports.handler ($:/plugins/Bob/ServerRoutes/get-files.js:88:27)
    at SimpleServer.requestHandler ($:/plugins/OokTech/Bob/commands/wsserver.js:158:15)
    at Server.emit (events.js:198:13)
    at parserOnIncoming (_http_server.js:691:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:17)
```

After digging into get-files.js I figured out that $tw.settings.filePathRoot was not set, passing an `undefined` value to `path.resolve`. I resolved this problem by setting the default `filePathRoot = "./Wikis"` in my settings.json. 

It seems that checking the Enable File Server checkbox in [FileServerSetup](https://github.com/OokTech/TW5-Bob/blob/09de6a2569fbdb95b17ca183bc2a9c824bcac3d8/ControlPanel/ServerTab/FileServerSetup.tid) is supposed to set this default value, but for whatever reason this didn't happen on my end.

---

I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [ ] Windows
- [ ] OSX
- [X] Linux
- [ ] Other

and using

- [X] The nodejs version
- [ ] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [X] I am using the newest version
- [X] The answer to my question isn't listed in the documentation or this isn't
  a question
- [X] This is not a duplicate issue
- [X] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

**Comment by inmysocks** [comment]
I am a bit confused by this one, because it is certainly supposed to make the default setting. I am going to instead add a full default settings file to Bob instead of having it packaged with the edition Bob uses.
That should clear up the problem when I do the next release.

**Comment by inmysocks** [comment]
there is now always a default value set, so this should be cleared up. Let me know if you run into it again.
