### ISSUE TITLE
Backup : SyntaxError: An invalid or illegal string was specified

### ISSUE THREAD

**Issue by silvyn** [OokTech/TW5-Bob#126]
Hi Jed,
So I am running Bob with Node.js on my web hosting account (Alwaysdata).

I just saw that the backup feature is a month old. (https://github.com/OokTech/TW5-Bob/issues/41).

I've the red alert when I open backups.

![image](https://user-images.githubusercontent.com/9981592/80348867-b4d72480-886e-11ea-8821-0535ed3719dc.png)

This happens to the main wiki (RootWiki folder) and also to others.

For RootWiki I don't have any functional files, but I had a first OK file for my other subwikis (but the following KOs).

When opening in text mode I don't see anything special, and I'm not sure how to help debugging.

I wonder if I'm the only one with this kind of problem.

Sylvain
---

I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [ ] Windows
- [ ] OSX
- [x] Linux
- [ ] Other

and using

- [x] The nodejs version
- [ ] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [x] I am using the newest version
- [x] The answer to my question isn't listed in the documentation or this isn't
  a question
- [x] This is not a duplicate issue
- [x] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

**Comment by inmysocks** [comment]
This is a problem with the backups, they were saved with the Bob plugin active which gives an error when you try to open the html files. That should have been fixed with the newest release, I am not certain that it got merged with the master branch of the repo. I will check and merge it if not.

**Comment by inmysocks** [comment]
The change has been on the master branch for 5 days, but I may not have updated the version number for it. Have you pulled from the repo in the last 5 days? If not that is the problem, if you have this is a new bug I need to track down.

In the meantime if there is an emergency the wikis should be able to be dragged and dropped into an empty wiki to recover their contents via import.

**Comment by silvyn** [comment]
Hum, well, I did a fresh install sunday, so yesterday. So maybe a new one.

**Comment by inmysocks** [comment]
Ok, I will try and find the problem and let you know if I make any progress.

**Comment by inmysocks** [comment]
I believe I found the error and it will be fixed in the next release. The fix is pushed on the nexe branch if you want to test it.

Remember that any backups made before installing the new version will still be broken.

**Comment by silvyn** [comment]
It's not urgent since it's just a testing of Bob on share hosting server, and without credential security, I'll shutdown this test instance. It was just to help you to find bug and fix it :)

**Comment by inmysocks** [comment]
I am closing this for now because it should be fixed in the upcoming release, please reopen it if the error persists.
