### ISSUE TITLE
WebSocket error:  TypeError: data.remove.split is not a function

### ISSUE THREAD

**Issue by pmgeuze** [OokTech/TW5-Bob#127]
Issue: Numerous functions in the Settings for Bob will not remain set when selected and the TW is Refreshed.

1. Clean install of BobWin.exe
2. Running Chrome Browser alongside the BobWin console
3. Open Control Panel, selected Enable backups.
4. Console shows ''WebSocket error:  TypeError: data.remove.split is not a function''
5. Deselect and Reselect, shows same console message.
6. Close tiddler with selected.
7. Tools->Refresh
8. Open Control Panel->Bob->Backups, Enable Backups is not selected. I also do not see or find the ''./backups'' folder.

I have the same issues with trying ''Enable File Server'' and other settings.

I have added BobWin in my Private Firewall exception list.

I am sure that this is something on my end, but if there is an easy solution I look forward to using your great program.

---

I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [x] Windows
- [ ] OSX
- [ ] Linux
- [ ] Other

and using

- [x] The nodejs version
- [ ] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [x] I am using the newest version
- [x] The answer to my question isn't listed in the documentation or this isn't
  a question
- [x] This is not a duplicate issue
- [x] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

**Comment by newmedicine** [comment]
Same setup. Websocket error: typeerror: data.remove.split is not a function when I perform most interesting options e.g.

- Enable File Server (click checkbox)
- Save media on server
- really any checkbox settings! (have to fiddle with manual settings directly - saving these works)

Sorry not huge amounts of info!

**Comment by pmgeuze** [comment]
I have also tried to copy the sections from conifguration.md to the settings.json to set the functions I want to work on. However, the Bob.win reports that the script is malformed (possibly a comma error) and uses the blank default setting.

If there is a manual way to force the settings in a script, I would be happy to do that.

**Comment by newmedicine** [comment]
I gave up in the end, basic node TW seems to do most of what I want (except running multiple wikis) and couldn't get either bundled BobEXE or any other the other iterations to work - loads of websocket errors.

**Comment by inmysocks** [comment]
These bugs should be fixed in the next release, but due to other work I am not sure how long it will be before I can make the next release.

**Comment by newmedicine** [comment]
Thanks!

**Comment by pmgeuze** [comment]
Thank you for letting me know that it was not something I had done wrong in the installation.

I enjoy your product and I look forward to seeing your future efforts.

Please let me know if you have a Patreon type platform.

Pieter-Michiel.

**Comment by inmysocks** [comment]
@pmgeuze I very rarely update it but we do have a Patreon https://www.patreon.com/OokTech
