### ISSUE TITLE
No Pugins/Themes/Languages/Editions Folder

### ISSUE THREAD

**Issue by brizzbane** [OokTech/TW5-Bob#129]
When I start up:

```
cd TiddlyWiki5
node ./tiddlywiki.js Wikis/BobWiki  --wsserver
```
I get:
> No Plugins Folder /home/brizz/Server/TiddlyWiki5/Plugins
> No Themes Folder /home/brizz/Server/TiddlyWiki5/Themes
> No Languages Folder /home/brizz/Server/TiddlyWiki5/Languages
> WebSocket error:  Error: ENOENT: no such file or directory, scandir '/home/brizz/Server/TiddlyWiki5/Editions'
> No Plugins Folder /home/brizz/Server/TiddlyWiki5/Plugins
> No Themes Folder /home/brizz/Server/TiddlyWiki5/Themes
> No Languages Folder /home/brizz/Server/TiddlyWiki5/Languages

I followed instructions exactly.  Though, first time I did try with --branch v5.1.22, but then after seeing above error, tried again w/out using latest version.

I figure I can just edit files, and rename the above uppercase directories to lowercase..  but then I thought, that maybe there is something more going on, and that maybe modifying would result in more errors from other parts of either TiddlyWiki, or TW5-Bob that expect capitalized directories. 

If that wasn't clear,

> /home/brizz/Server/TiddlyWiki5/plugins
> /home/brizz/Server/TiddlyWiki5/themes
> /home/brizz/Server/TiddlyWiki5/languages
> /home/brizz/Server/TiddlyWiki5/editions

exist.
 

I was surprised I did not see another issue about this.  I apologize if I missed something.  I did see the TIDDLYWIKI_EDITION_PATH instructions.  But I'm not using a global install, AND, that would just cover edition and plugin directory.

Thank you for any help or guidance you can provide.

I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [ ] Windows
- [ ] OSX
- [x] Linux
- [ ] Other

and using

- [x] The nodejs version
- [ ] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [x] I am using the newest version
- [x] The answer to my question isn't listed in the documentation or this isn't
  a question
- [x] This is not a duplicate issue
- [x] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

**Comment by brizzbane** [comment]
I think I figured out what I need to do/what file to edit..  

> ./Wikis/BobWiki/settings/settings.json

..modify existing to lowercase:

```
  "wikisPath": "./wikis",
  "pluginsPath": "./plugins",
  "themesPath": "./themes",
```



and needed to add:

```
  "editionsPath": "./editions",
  "languagesPath": "./languages",
```

**Comment by linonetwo** [comment]
For people not using Edition folder: https://github.com/OokTech/TW5-Bob/issues/137
