### ISSUE TITLE
[Bug] *.tid files without a defined Type have it forced to text/vnd.tiddlywiki

### ISSUE THREAD

**Issue by joshuafontany** [OokTech/TW5-Bob#131]
I saw a change about loading MIME types, but I think this had an unintended halo bug where tiddlers of *.tid _without_ a defined Type get it auto-set to "text/vnd.tiddlywiki". Just wondering if that was inteded?

---

I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [x] Windows
- [ ] OSX
- [ ] Linux
- [ ] Other

and using

- [x] The nodejs version
- [ ] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [x] I am using the newest version
- [x] The answer to my question isn't listed in the documentation or this isn't
  a question
- [x] This is not a duplicate issue
- [x] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

**Comment by inmysocks** [comment]
I haven't been able to get this behaviour, it isn't intended behaviour.

**Comment by joshuafontany** [comment]
Yeah, I'm not seeing this either any more. Closed. Will reopen if it pops back up.
