### ISSUE TITLE
Git's "discard change" create file with _1 suffix

### ISSUE THREAD

**Issue by linonetwo** [OokTech/TW5-Bob#138]
---

I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [ ] Windows
- [x] OSX
- [ ] Linux
- [ ] Other

and using

- [x] The nodejs version
- [ ] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [x] I am using the newest version
- [x] The answer to my question isn't listed in the documentation or this isn't
  a question
- [x] This is not a duplicate issue
- [x] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

Watch my screenshot video gif below:

![gitdiscardchange](https://user-images.githubusercontent.com/3746270/86539000-14ffdc00-bf2c-11ea-850d-f676d2379468.gif)

When Git fastly deletes and recreate the file, seems Bob will create an `Index_1.tid`, and if I delete that file, then Bob will show `Index.tid` is deleted. But actually that file is still on the disk. I have to restart Bob to get it back to the browser.

This won't happen all the time. Sometimes when I discard change in the GitHub Desktop, Bob just works fine. But one out of two times this but will happen.

Maybe this is related to https://github.com/OokTech/TW5-Bob/pull/134 ?

**Comment by inmysocks** [comment]
If you use some other form of syncing you will have this problem. You can turn off the file system monitor or not use other syncing software or git while Bob is running.

**Comment by joshuafontany** [comment]
I have been wanting to use Bob to control Git for my wikis backup/push etc. I think it would be work figuring out a way to allow Bob to turn off the File System Monitor internally before running tasks that might invoke outside processes, then back on afterwards. I wonder if this issue has come up with other projects that use git...

**Comment by linonetwo** [comment]
Hi @inmysocks  , actually I'm using Bob because I'm developing an App that auto-sync tw data to Github, so we can use private repo of Github to build cross-platform privacy-first TW app.

So I really need Bob to work with git operations...

Can I turn off file system monitor on the fly and reopen it after git operation so it knows what happened correctly? So I don't need to restart server after git operation just like before I meet Bob.

**Comment by linonetwo** [comment]
@joshuafontany I don't think we should turn off the File System Monitor, because if so then Bob won't know files changed by git.

**Comment by linonetwo** [comment]
When Github Desktop discards a change, it moves the file to trash and re-check-out that file from the previous commit. This happens very quick.
 
Why would this cause this bug in Bob?

Maybe

1. move file to trash
2. this change is monitored by Bob, so it delete the tiddler in the browser (it disappeared for half a second)
3. git check out Index.tid
4. Somehow bob added that file back to fs, so there is Index_1.tid

**Comment by linonetwo** [comment]
Maybe add a debounce to fs.watch can solve this?

I'm using

```
function watchFolder(wikiRepoPath, wikiFolderPath, githubRepoUrl, userInfo) {
  fs.watch(
    wikiFolderPath,
    { recursive: true },
    debounce((_, fileName) => {
      if (topLevelFoldersToIgnored.some(name => fileName.startsWith(name))) return;
      if (frequentlyChangedFileThatShouldBeIgnoredFromWatch.has(fileName)) return;
      console.log(`${fileName} change`);

      debounceCommitAndSync(wikiRepoPath, githubRepoUrl, userInfo);
    }, 500),
  );
  console.log(`wiki watch ${wikiFolderPath} now`);
}
```

In my sync script. What's your opinion @inmysocks ?

**Comment by linonetwo** [comment]
I dive into this, found sometimes when this error occurs, it run into this if branch:

https://github.com/OokTech/TW5-Bob/blob/03e2ea4cdcedc34f8d69cba5261830e2fa587092/FileSystem/FileSystemMonitor.js#L49-L62

This is because:

1. git delete file on fs
1. `fs.watch` detect this change
1. if git checkout is fast enough, then there is no trouble; but it is a bit slow...
1. `fs.stat` found this file 'ENOENT', it thinks the file has been removed
1. so Bob deletes the tiddler in the browser using `$tw.Bob.DeleteTiddler`

then git check out the file...so it goes to this else branch, which generates a new title

https://github.com/OokTech/TW5-Bob/blob/03e2ea4cdcedc34f8d69cba5261830e2fa587092/FileSystem/FileSystemMonitor.js#L62-L120

**Comment by linonetwo** [comment]
If git cause error:

```
----
eventType "rename" Index.tid
err.code "ENOENT"
Deleted tiddler Index
----
eventType "rename" Index.tid
fileStats.isFile() true
```

if it works fine

```
----
eventType "rename" Index.tid
----
eventType "rename" Index.tid
fileStats.isFile() true
```

a typical race condition bug.

**Comment by linonetwo** [comment]
Oh, I know what's exactly going on!

1. If `fs.watch` say the file is modified, Bob sync from fs to browser, `$tw.syncadaptor.saveTiddler` will use fs.writeFile, because it detects there is a tiddler in the browser, so it believes there is a corresponding file in the fs, so it should just modify the file in the fs
1. If `fs.watch` say the file is created or deleted ( eventType === 'rename' ), and fs.stat confirm that we are creating a file, then Bob try to sync from fs to browser use `$tw.syncadaptor.saveTiddler` same as above

But!

`$tw.syncadaptor.saveTiddler` found no such tiddler in the browser, so it guess there is no such file in the fs too.

So it will try to create a new tiddler in the fs. And there is already a tiddler with that name in the fs, so it append `_1` to the name.

So the fix is very simple, we can just delete the file in the fs first, then use `$tw.syncadaptor.saveTiddler`, so it will create a tiddler with a correct file name.
