### ISSUE TITLE
Config port on runtime or command line

### ISSUE THREAD

**Issue by linonetwo** [OokTech/TW5-Bob#139]
---

I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [ ] Windows
- [x] OSX
- [ ] Linux
- [ ] Other

and using

- [x] The nodejs version
- [ ] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [x] I am using the newest version
- [x] The answer to my question isn't listed in the documentation or this isn't
  a question
- [x] This is not a duplicate issue
- [x] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

I'm trying to create https://github.com/tiddly-gittly/TiddlyGit-Desktop which allow user to create nodejs wiki that sync to github using GUI, and I'm adding Bob into it.

I need to control which port bob websocket server is in, it by default is controlled by settings/settings.json , but I need this to be programmatically changed, just like I'm booting tw using:

```js
$tw.boot.argv = [
  '+plugins/tiddlywiki/filesystem',
  '+plugins/tiddlywiki/tiddlyweb',
  tiddlyWikiFolder,
  '--listen',
  `anon-username=${userName}`,
  `port=${tiddlyWikiPort + 1}`,
  'host=0.0.0.0',
  'root-tiddler=$:/core/save/lazy-images',
  '--wsserver', // port config in settings/settings.json , can't be set here
];

try {
  execSync(`find ${tiddlersFolder} -name '*StoryList.tid' -delete`);
} catch (error) {
  console.log(String(error));
}

module.exports = function startNodeJSWiki() {
  $tw.boot.boot();
}
```

So how to change wsserver port to `${tiddlyWikiPort}` ?

**Comment by inmysocks** [comment]
The --listen and --wsserver commands both set up a server for tiddlywiki, so having both is redundant. If both run it will almost certainly cause problems.
If you have Bob in a wiki it disables the filesystem and tiddlyweb plugins because their functions interfere with each other.

the --wsserver command doesn't take any command line arguments other than the location of the index wiki.

I think the only way to do what you want is to make a new server command.

**Comment by linonetwo** [comment]
I have to do so:

```js
const bobServerConfig = JSON.parse(fs.readFileSync(bobServerConfigPath, 'utf-8'));
bobServerConfig.pluginsPath = `./${wikiFolderName}/plugins`;
bobServerConfig.themesPath = `./${wikiFolderName}/themes`;
bobServerConfig.editionsPath = `./${wikiFolderName}/`;
bobServerConfig.wikiPathBase = repoFolder;
bobServerConfig['ws-server'].port = tiddlyWikiPort;
fs.writeFileSync(bobServerConfigPath, JSON.stringify(bobServerConfig, null, '  '));

process.env['TIDDLYWIKI_PLUGIN_PATH'] = `${tiddlyWikiFolder}/plugins`;
process.env['TIDDLYWIKI_THEME_PATH'] = `${tiddlyWikiFolder}/themes`;
$tw.boot.argv = [
  '+plugins/OokTech/Bob',
  tiddlyWikiFolder,
  '--wsserver',
];
```

Recreate config json before wiki started
