### ISSUE TITLE
Saving changes in new child wikis to the filesystem

### ISSUE THREAD

**Issue by iliekprogrammar** [OokTech/TW5-Bob#141]
Make sure you read contributing.md and check the correct boxes below and then
add your issue text here.
If you don't than the issue will be tagged as spam and closed or deleted.

---

I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [ ] Windows
- [ ] OSX
- [ ] Linux
- [x] Other

and using

- [x] The nodejs version
- [ ] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [x] I am using the newest version
- [X] The answer to my question isn't listed in the documentation or this isn't
  a question
- [X] This is not a duplicate issue
- [X] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

--

Apologies if my formatting offends your dyslexia, will reduce/change them if it's too much.

Pressing Save Changes in an empty child wiki results in a prompt to save it as a single HTML file. I'm unsure if this is the expected behaviour or not.

### What I did so far:

1. Install tiddlywiki globally.
2. Create an empty tiddlywiki ``~/Documents/TW``. I'll refer it as ``$wiki``. This is done with the following:    
``$ tiddlywiki --init``
3. Clone TW5-Bob in the directory ``$wiki/plugins/Bob`` with the following:    
``$ git clone --depth=1 'https://github.com/OokTech/TW5-Bob.git' "$wiki/plugins/Bob"``
4. Add ``settings/settings.json`` with the following:    
```json
    {
      "editionsPath": "./editions",
      "pluginsPath": "./plugins",
      "themesPath": "./themes",
      "wikisPath": "./wikis",
      "wikiPathBase": "/home/me/Documents/TW"
    }
```
5. Run the node server:    
``$ tiddlywiki "$wiki" --wsserver``
6. Visit ``127.0.0.1:8080`` in a browser and go to ``$:/ControlPanel`` > Bob Settings > Wiki Management
7. Create an empty wiki, named TW-Empty. Then, I navigate to it by opening the link in Wiki Listing.
8. Create a new tiddler and press Save Changes on the sidebar. The result was the single HTML file you'd get with a usual empty wiki.

Does TW5-Bob has a special way of handling it or does TW5-Bob isn't responsible for the child wiki at all? If TW5-Bob isn't responsible, do i need to find a filesystem saver for the child wiki?

**Comment by inmysocks** [comment]
When you put bob inside the $wiki folder it is only available to $wiki. If the plugin is available it is added to every wiki served by bob, so put the plugin into './plugins' like you put in the settings.json, not inside './$wiki/plugins'

**Comment by iliekprogrammar** [comment]
Ahh, I got it working now. Can I get a confirmation with :+1:  on these steps?

Step 1 and 2 are the same.
3. Clone TW5-Bob in one of the paths in ``$TIDDLYWIKI_PLUGIN_PATH`` with the following:    
``$ git clone --depth=1 'https://github.com/OokTech/TW5-Bob.git' "$plugin/OokTech/Bob"``
4. Add ``$wiki/settings/settings.json`` with the following:    
```json
    {
      "editionsPath": "./editions",
      "pluginsPath": "./plugins",
      "themesPath": "./themes",
      "wikisPath": "./wikis",
      "wikiPathBase": "/home/me/Documents/TW"
    }
```
5. Add TW5-Bob plugin into ``tiddlywiki.info``:
```json
    "plugins": [
      "OokTech/Bob"
    ]
```
The continuing steps are also the same.
