### ISSUE TITLE
Bob Saver configuration incorrectly named in documentation

### ISSUE THREAD

**Issue by linonetwo** [OokTech/TW5-Bob#144]
- [ ] Windows
- [x] OSX
- [ ] Linux
- [ ] Other

and using

- [x] The nodejs version
- [ ] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [x] I am using the newest version
- [x] The answer to my question isn't listed in the documentation or this isn't
  a question
- [ ] This is not a duplicate issue
- [x] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

---

I have

`Bob saver server running on 127.0.0.1:61192`

Even I have a following generated config file:

```js
{
  "serverName": "TiddlyGit-Desktop",
  "persistentUsernames": "yes",
  "heartbeat": {
    "interval": 200
  },
  "enableBobSaver": "no",
  "saver": {
    "disable": "yes"
  },
  "pluginsPath": "./plugins",
  "themesPath": "./themes",
  "editionsPath": "./",
  "wikiPathBase": "/Users/linonetwo/Desktop/tiddlywiki",
  "ws-server": {
    "port": 5212,
    "host": "0.0.0.0",
    "autoIncrementPort": false,
    "rootTiddler": "$:/core/save/lazy-images"
  }
}
```

**Comment by linonetwo** [comment]
Seems you are using a different config than the one in the documentation:

https://github.com/OokTech/TW5-Bob/blob/6c0db8010e803fd266d04a6a4b9c4562f4c849e0/commands/ws-server.js#L390

**Comment by inmysocks** [comment]
I will update the documentation, but why not use the settings in the control panel to disable it?

**Comment by linonetwo** [comment]
Oh, I'm creating a desktop app, that will generate a wiki for user in a click. And I need to make a template that works with my app, then copy all these stuff and Bob plugin to user's desktop. 

I need to set some default things for the user in advance.

**Comment by inmysocks** [comment]
Ok, I was wrong and the UI wouldn't disable it either. The configuration name is going to be `enableBobSaver` and It will be fixed for the next release.
