### ISSUE TITLE
Server crashing on Wiki reload in Chrome and randomly

### ISSUE THREAD

**Issue by AnthonyMuscio** [OokTech/TW5-Bob#153]
I recently started to have the server windows of Bob.exe fail, when I load or reload a Bob wiki (bobwin.exe) imediatly in chrome but not in FireFox immediately (both latest release as at posting), it seems to fail a short time later. The default wiki loads fine.

By loading Bobwin.exe in a command window, I see it exit with the following message

```
internal/validators.js:112
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:375:7)
    at FSWatcher.<anonymous> ($:/plugins/OokTech/Bob/FileSystemMonitor.js:43:31)
    at FSWatcher.emit (events.js:210:5)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:131:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

I sometimes see this of late
`WebSocket error:  TypeError: Cannot read property 'fields' of undefined`

Thanks in advance and I am happy to test or record anything that may help.

Tones

---

I am running

- [x] Windows
- [ ] OSX
- [ ] Linux
- [ ] Other

and using

- [ ] The nodejs version
- [x] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [x] I am using the newest version (Bob version 1.6.0b1)
- [x] The answer to my question isn't listed in the documentation or this isn't
  a question
- [x] This is not a duplicate issue
- [x] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

**Comment by AnthonyMuscio** [comment]
Hi,

I am still getting this error (below), It now occurs within minutes after loading boxwin.exe and seems to be related to the loading or saving of any wiki.

Another instance (old copy)  of with Bob version 1.6.0b1 on the same PC (different folder) has a similar problem, I create and open a new wiki and I navigate to it, and reloads loads but the "WARNING: The connection to server hasn't been established yet". Will not go away, and I can't save but unlike the first instance the server does not abend. 

So the two thing in common so far is this is occurring on TiddlyWiki version 5.1.22 with Bob version 1.6.0b1 OR my computer as a whole.

However it is working running TiddlyWiki version 5.1.21 with Bob version 1.3.1 on the old copy works and does not fail. Including with TiddlyWiki version 5.1.21 with Bob version 1.4.0b2

Its getting critical now because I can not access work details. 

-  Can I revert to a prior version of bob safely?


```
No Themes Folder C:\Data\TW5\!TW-Tools\Themes
internal/validators.js:112
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:375:7)
    at FSWatcher.<anonymous> ($:/plugins/OokTech/Bob/FileSystemMonitor.js:43:31)
    at FSWatcher.emit (events.js:210:5)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:131:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by inmysocks** [comment]
There isn't anything special about the wiki files, just change the executable you are using. But I suspect the executable version isn't the problem.
Generally those problems come from using an external file syncer or backup utilities.

**Comment by AnthonyMuscio** [comment]
Hi, I still have the problem somewhat but are moving the existing wikis into new installs. 

- This seems as simple as copying their folders and using Wiki Listing update list.

I will make one bobexe version local only, one one with a smaller set of wikis available on the LAN.

**To return to my prior setup perhaps you can advise me how I may do the following;**

- Have a given Bob server available on a localhost address of 17.0.**4**.84 (as an example), using port 80 so there is no need to include port in the address. This server would not be made available on the LAN

**I plan to have a separate bob server I run when needed**
- Have a given Bob server available on a localhost address of 17.0.**5**.84 (as an example), using port 80 so there is no need to include port in the address.
- Have that same server available on the LAN at IP Addresses 192.168.1.84 port 80 which is an additional IP on the current computer, but may be moved one day. I would like to avoid using 0.0.0.0 as this binds to all 10 of this computers LAN IP addresses. This works on native node by using 192.168.1.84 as the IP Address rather than 0.0.0.0 but seems a problem on Bob.
- This would also stop interference with an Apache server on my key IP Address 192.168.1.119, and TiddlyServer on 192.168.1.81
- An optional extra would be with this same server if I can also have Bob saver server running on say 192,168.1.85:61192 or 192.168.1.84:61192 

Thanks Jed for creating this, I am one of you patreon's, but we should try and build up you supporter numbers, I hope to do this as well in the future. I will have a go at promoting this again next time i have a relevant post.
Tones

**Comment by inmysocks** [comment]
If you have a separate question open a separate issue, don't put unrelated questions in existing issues.

**Comment by AnthonyMuscio** [comment]
This is related, totally It may not be from a technical perspective but it is from an application perspective. I have done a fresh exe install to get a way from mystery failures. I am seeking your guidance to configure bob to achieve similar to what I can configure on Node and TiddlyServer and I believe attempting to configure these caused the intermittent failures, but I am only guessing, and given your solution "worked" to halt crashes, this now seems the case. I will Open a new one but please be aware I am not trying to do anything improper, although I "feel" you always think I am for some reason.
