### ISSUE TITLE
Can't uncheck "Automatically open browser when BobEXE starts " setting

### ISSUE THREAD

**Issue by amreus** [OokTech/TW5-Bob#154]
Using BobWin.exe 1.6.2 on WIndows 10, TW 5.1.22.

Go to ControlPanel -> Bob -> Server Settings

Attempting to uncheck the "Automatically open browser when BobEXE starts " option does not work. 

Probably related is if you look at the settings file, the setting "supressBrowser" has a value of false but it not quoted like the other settings values. 

Make sure you read contributing.md and check the correct boxes below and then
add your issue text here.
If you don't than the issue will be tagged as spam and closed or deleted.

---

I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [x] Windows
- [ ] OSX
- [ ] Linux
- [ ] Other

and using

- [ ] The nodejs version
- [x] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [x] I am using the newest version
- [x] The answer to my question isn't listed in the documentation or this isn't
  a question
- [x] This is not a duplicate issue
- [x] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

**Comment by inmysocks** [comment]
I am fixing this and uploading version 1.6.2r2 now, it may be a while because my connection is unstable.

**Comment by amreus** [comment]
Works, thanks.
