### ISSUE TITLE
Needless Console Debugging Output

### ISSUE THREAD

**Issue by amreus** [OokTech/TW5-Bob#157]
Hello.  These 2 debugging lines are filling up the server console. I'm not sure if you consider them an issue, but I just wanted to bring them to your attention. Thanks.

https://github.com/OokTech/TW5-Bob/blob/61bfcd84b3f9bca3e6d5a14c093f534f04789335/ServerRoutes/ServerRoutes/get-fetch-tiddlers.js#L29

https://github.com/OokTech/TW5-Bob/blob/61bfcd84b3f9bca3e6d5a14c093f534f04789335/ServerRoutes/ServerRoutes/get-list-wikis.js#L24

**Comment by inmysocks** [comment]
They are old debugging checks that I missed when preparing for the release, they will be removed from the next release.
