### ISSUE TITLE
Javascript Date() constructor does not accept TiddlyWiki date format as input, nor empty strings.

### ISSUE THREAD

**Issue by amreus** [OokTech/TW5-Bob#159]
Using BobWin.exe 1.6.2r2, Windows 10, latest Firefox 81.0.2.

There are several places in the code where there is a call to (for example) `new Date(SomeObject.fields.created)`

I'm mostly interested in these 2:

https://github.com/OokTech/TW5-Bob/blob/61bfcd84b3f9bca3e6d5a14c093f534f04789335/ServerRoutes/ServerRoutes/post-push.js#L48

https://github.com/OokTech/TW5-Bob/blob/61bfcd84b3f9bca3e6d5a14c093f534f04789335/ServerRoutes/ServerRoutes/post-push.js#L49

These lines return "NaN"

```
// empty string
$tw.utils.stringifyDate(new Date(""));
==> "NaNNaNNaNNaNNaNNaNNaN"

// TiddlyWiki date
$tw.utils.stringifyDate(new Date("20201016232045362"));
==> "NaNNaNNaNNaNNaNNaNNaN"
```

**Comment by inmysocks** [comment]
This works as intended. All of the tools that I use to work with the api send the dates as stringifyed javascript dates.

Please read and follow the guidelines for making a bug report or feature request https://ooktech-public.gitlab.io/guidelines/

**Comment by amreus** [comment]
Gotcha, thanks.
