### ISSUE TITLE
"sub wiki" stopped working - please help

### ISSUE THREAD

**Issue by s-kaczmarek** [OokTech/TW5-Bob#160]
Hi, I have "main" wiki and "sub wiki" that I run by clicking on "wikis" tab in menu. I didn't faced any issues yesterday, today after launching this "sub wiki" I get error:

NodeSettings - Parsed raw settings.
Added route /^\/personal-wiki\/?$/
TiddlyWiki version 5.1.21 with Bob version 1.4.0b4
Bob saver server running on 127.0.0.1:61192
Serving on 127.0.0.1:8080
(press ctrl-C to exit)
new connection
No Languages Folder /home/slawek/mnt/decrypted/personal.mnt/notatki/personal-wiki/Languages

<--- Last few GCs --->

[8745:0x30aac70]   119934 ms: Mark-sweep 817.6 (864.3) -> 817.6 (832.8) MB, 49.4 / 0.0 ms  (average mu = 0.896, current mu = 0.000) last resort GC in old space requested
[8745:0x30aac70]   119985 ms: Mark-sweep 817.6 (832.8) -> 817.6 (832.8) MB, 51.0 / 0.0 ms  (average mu = 0.805, current mu = 0.000) last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x200b64a041bd]
Security context: 0x2a796751e589 <JSObject>
    1: DoJoin(aka DoJoin) [0x1264dfea2629] [native array.js:~87] [pc=0x200b64ad9bac](this=0x171d643822e1 <undefined>,l=0x1d6820bc4871 <JSArray[56]>,m=56,A=0x171d64382381 <true>,w=0x171d64382441 <String[0]: >,v=0x171d643823f1 <false>)
    2: Join(aka Join) [0x1264dfea2679] [native array.js:~112] [pc=0x200b64af4df4](this=0x171d643822e1 <undefined>,l=0x1d6820bc...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/home/slawek/mnt/decrypted/personal.mnt/notatki/personal-wiki/BobLinux]
 2: 0x91d94c [/home/slawek/mnt/decrypted/personal.mnt/notatki/personal-wiki/BobLinux]
 3: v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/home/slawek/mnt/decrypted/personal.mnt/notatki/personal-wiki/BobLinux]
 4: v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/home/slawek/mnt/decrypted/personal.mnt/notatki/personal-wiki/BobLinux]
 5: 0xe8d332 [/home/slawek/mnt/decrypted/personal.mnt/notatki/personal-wiki/BobLinux]
 6: v8::internal::Heap::AllocateRawWithRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/home/slawek/mnt/decrypted/personal.mnt/notatki/personal-wiki/BobLinux]
 7: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/home/slawek/mnt/decrypted/personal.mnt/notatki/personal-wiki/BobLinux]
 8: v8::internal::Runtime_StringBuilderConcat(int, v8::internal::Object**, v8::internal::Isolate*) [/home/slawek/mnt/decrypted/personal.mnt/notatki/personal-wiki/BobLinux]
 9: 0x200b64a041bd
/home/slawek/dot/scripts/bin/second-brain: line 12:  8745 Aborted                 (core dumped) $PERSONAL_WIKI_LOCATION/BobLinux

Please help!

**Comment by inmysocks** [comment]
That error is from having a wiki that is too large for node to hold in memory. In your case it looks like something around 800mb.

My guess is that you have some very large tiddlers in your wiki that are using up all the memory.

I have not had any trouble with running out of memory, but I don't have any very large wikis.

My suggestions are to make all the media external, and if possible to split up into more wikis.

**Comment by inmysocks** [comment]
Updating Bob to the newest version may also help.

**Comment by s-kaczmarek** [comment]
Thanks inmysocks, I moved temporally some of my tiddlers to another location and wiki is running now. I think, that I will have to split my data to serious of "sub wikis", as you mentioned.

**Comment by s-kaczmarek** [comment]
Thanks inmysocks, I moved temporally some of my tiddlers to another location and wiki is running now. I think, that I will have to split my data to serious of "sub wikis", as you mentioned.
