### ISSUE TITLE
I can't run newest version - 1.6.2 Linux 64

### ISSUE THREAD

**Issue by s-kaczmarek** [OokTech/TW5-Bob#161]
Hello,

I faced following issue while trying to run Bob 1.6.2 for Linux 64:

> Error executing boot module $:/plugins/OokTech/Bob/FileSystemMonitor.js: {}
> 
> $:/plugins/OokTech/Bob/FileSystemMonitor.js:24
> if($tw.node && $tw.settings.disableFileWatchers !== 'yes') {
>                             ^
> 
> TypeError: Cannot read property 'disableFileWatchers' of undefined
>     at $:/plugins/OokTech/Bob/FileSystemMonitor.js:24:29
>     at $:/plugins/OokTech/Bob/FileSystemMonitor.js:229:3
>     at Script.runInContext (vm.js:127:20)
>     at Script.runInNewContext (vm.js:133:17)
>     at Object.runInNewContext (vm.js:299:38)
>     at Object.$tw.utils.evalSandboxed (/home/slawek/mnt/data/sandbox/tiddlywiki-testy/upgrade-test/TiddlyWiki5

> 
> /boot/boot.js:530:5)
>     at Object.$tw.modules.execute (/home/slawek/mnt/data/sandbox/tiddlywiki-testy/upgrade-test/TiddlyWiki5/boot/boot.js:806:15)
>     at /home/slawek/mnt/data/sandbox/tiddlywiki-testy/upgrade-test/TiddlyWiki5/boot/boot.js:846:30
>     at Object.$tw.utils.each (/home/slawek/mnt/data/sandbox/tiddlywiki-testy/upgrade-test/TiddlyWiki5/boot/boot.js:135:12)
>     at Object.$tw.modules.forEachModuleOfType (/home/slawek/mnt/data/sandbox/tiddlywiki-testy/upgrade-test/TiddlyWiki5/boot/boot.js:845:12)

**Comment by inmysocks** [comment]
I haven't been able to get this error. I fixed what is causing the problem for you, but if you could give me more information about your setup so I can try and prevent similar things in the future.

I will be releasing the next version sometime this next week.

**Comment by s-kaczmarek** [comment]
Cool, thanks, I will try new release in next week. What kind of data do you need?

**Comment by niconfus** [comment]
I have the same issue both on Debian Buster 10.6 with kernel 4.19.0-12-amd64 and Fedora 32 with kernel 5.8.17-200.fc32.x86_64.

I downloaded the 1.6.2r2 [executable](https://github.com/OokTech/TW5-BobEXE/releases/download/1.6.2r2/BobLinux) and ran it in my existing TW5-Bob wiki, but it exited with the same error. I also tried running it in an empty directory and it created the default wiki files, but then crashed again.

I would be happy to provide any additional information if that would help.

**Comment by acarv** [comment]
Same here on Windows 10 with a fresh manual installation and on the default index wiki but with the error : 
```
$:/plugins/OokTech/Bob/ServerSide.js:813
  if(data.decoded) {
          ^
TypeError: Cannot read property 'decoded' of undefined
```
This is a plain manual installation with the two git clones and just accessing the index for the first time. Node.js version is v14.15.0

**Comment by inmysocks** [comment]
I think that these problems should be fixed in the new release that is about to come out. I haven't been able to replicate them so I can not be certain. Please let me know one way or the other once I do the release.

**Comment by niconfus** [comment]
I tried the new version 1.7.0b1 release and it did not crash like 1.6.2r2, so thank you for the update.
