### ISSUE TITLE
$tw.settings is undefined

### ISSUE THREAD

**Issue by MerlinB** [OokTech/TW5-Bob#163]
This commit https://github.com/OokTech/TW5-Bob/commit/4c5ff7502dcffb765ee00e2ebeb7b058b9a8a70c results in
```
Error executing boot module $:/plugins/OokTech/Bob/AutomaticBackups.js: {}

$:/plugins/OokTech/Bob/AutomaticBackups.js:43
  $tw.settings.backups = $tw.settings.backups || {};
                                      ^

TypeError: Cannot read property 'backups' of undefined
    at $:/plugins/OokTech/Bob/AutomaticBackups.js:43:39
    at $:/plugins/OokTech/Bob/AutomaticBackups.js:130:3
    at Script.runInContext (vm.js:142:18)
    at Script.runInNewContext (vm.js:147:17)
    at Object.runInNewContext (vm.js:302:38)
```
for me.

Followed the manual install for node.js

---

I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [ ] Windows
- [ ] OSX
- [x] Linux
- [ ] Other

and using

- [x] The nodejs version
- [ ] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [x] I am using the newest version
- [x] The answer to my question isn't listed in the documentation or this isn't
  a question
- [x] This is not a duplicate issue
- [x] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

**Comment by bryanjnorton** [comment]
I have the same problem. 
-B

**Comment by inmysocks** [comment]
This should be fixed in the new release that I am hoping to put out in an hour or two.
