### ISSUE TITLE
Unable to create new wiki from existing single-file TW5 html file

### ISSUE THREAD

**Issue by dixonge** [OokTech/TW5-Bob#166]
I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [ ] Windows
- [x] OSX
- [ ] Linux
- [ ] Other

and using

- [ ] The nodejs version
- [x] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [x] I am using the newest version **(version 1.7.0b1)**
- [x] The answer to my question isn't listed in the documentation or this isn't
  a question
- [x] This is not a duplicate issue
- [x] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

I have tried twice to create a new wiki inside Bob from an existing single-file wiki. I can open this other wiki in my browser directly, so I know that it is a functional wiki with many journal entries and many projects/tasks from Projectify.

Inside Bob, I click the link for the new wiki and it opens in the browser (127.0.0.1:8080/newwiki) but the content is exactly the same as the Index Bob wiki. None of the tiddlers from the single-file wiki are imported.

**Comment by dixonge** [comment]
Switched to v1.6.2r2 - same result.

I then created a new wiki from the empty edition. I opened this, then imported my single-file wiki directly. This worked just fine as expected.

I also created a new wiki from an existing single-file wiki html file. This still did not work. But I then used the normal import routine from inside this Bob-created wiki, and *that* did work as expected. I relaunched this wiki from inside the Bob index wiki, and it did still load.

So this inability to create a new wiki from an existing one persists across both versions (1.6.2r2 and 1.7.0b1)

**Comment by nicksiv** [comment]
Second that.
I tried single file wiki import. The wiki was created but without any tiddlers inside.
(On Linux, with manual nodejs version)

**Comment by inmysocks** [comment]
I haven't had much use for the feature and I overlooked it when updating some things on the back-end, it should be added back in for the next release.

**Comment by inmysocks** [comment]
The bug that caused this issue is fixed, if this (or a similar) problem comes up again please make a new issue.
