### ISSUE TITLE
WebSocket error:  TypeError: Cannot create property 'enable' on string '{<<__name__>>: <<__value__>>}'

### ISSUE THREAD

**Issue by PARC6502** [OokTech/TW5-Bob#169]
I'm getting some errors when trying to set Bob settings. Specifically, these behaviours happened when adjusting the Backup settings. After seeing this happen, I tested by trying to enable the file server and the same thing happened.

Here are the behaviours:

1. After adjusting a setting, the log says `Wrote settings file`, but the setting isn't changed. This is very clear with the 'Enable' checkbox for backups or the file server where it will uncheck itself. 
2. I receive the websocket error mentioned in the title. `WebSocket error:  TypeError: Cannot create property 'enable' on string '{<<__name__>>: <<__value__>>}'` 
3. Whilst writing this issue and testing the enable backup checkbox, I got a new error: `WebSocket error:  TypeError: Cannot create property 'enable' on string 'yes'`

All of these behaviours happened on a fresh install of Bob. I had the same behaviours on my old install, but I was having some other issues too, which resulted in me trying with a fresh install. I've tested with both TiddlyWiki 5.1.22 and 5.1.23 and have updated to the newest LTS node release.

---

I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [x] Windows
- [ ] OSX
- [ ] Linux
- [ ] Other

and using

- [x] The nodejs version
- [ ] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [x] I am using the newest version
- [x] The answer to my question isn't listed in the documentation or this isn't
  a question
- [x] This is not a duplicate issue
- [x] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

**Comment by inmysocks** [comment]
These problems should be fixed in the next release.

**Comment by s-kaczmarek** [comment]
I got the same problem on Linux version. TiddlyWiki version 5.1.23 with Bob version 1.7.1

**Comment by inmysocks** [comment]
There have been a lot of updates since this issue was made, I  believe that the problem has been fixed so I am closing the issue, if it is still a problem comment here and I will reopen it.
