### ISSUE TITLE
Bug: TW5-Bob v1.7.1, "Make wikis available on local network" not working anymore

### ISSUE THREAD

**Issue by domalex** [OokTech/TW5-Bob#170]
Since TW5-Bob v1.7.1 the service can not be enabled anymore. I guess it has something to do with the change to https. With the old settings.json file of v1.6.2, where I enabled the service previously, I can access my wikis (http not https) despite Bob's control panel  says "Wiki Server Address (not available on local network) ". However, I cannot disable or re-enable the service within Bob's settings tiddler.

The settings.json show one difference: The host changed from 0.0.0.0 to 127.0.0.1

I hope this report helps to fix the issue.

---

- [ ] Windows
- [ ] OSX
- [x] Linux (Arch Linux (PC), Arch Linux ARM (Raspberry Pi))
- [ ] Other

and using

- [x] The nodejs version
- [ ] The single file executable

Before posting, I read [issue guidelines](./IssueGuidelines.md) and:

- [x] I am using the newest version
- [x] The answer to my question isn't listed in the documentation or this isn't
  a question
- [x] This is not a duplicate issue
- [x] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

**Comment by inmysocks** [comment]
This should be fixed in the next release

**Comment by domalex** [comment]
Thank you for the update

**Comment by inmysocks** [comment]
It has been a long time and this should be fixed, at least in the newest version, so I am closing this issue. If it is still a problem leave a comment letting me know and I will reopen it.
