### ISSUE TITLE
How to start subwiki after clicking on link?

### ISSUE THREAD

**Issue by s-kaczmarek** [OokTech/TW5-Bob#178]
Hi, is there any way to create a link to tiddler in another wiki on the same Bob server and make this link to start that wiki after clicking? 

Let's say that I browse wiki1 and there is a link to tiddler in wiki2, but wiki2 is not running. I would like bob to start that wiki after clicking and move to that tiddler.

Hope that is clear. Is something like that possible?

**Comment by inmysocks** [comment]
that should happen automatically, whenever you open a link to a wiki it should start.

**Comment by s-kaczmarek** [comment]
Oh yes it does! It probably didn't work in one of the previous versions and I haven't tested that feature in the latest one. All works good, please close the issue! :)
