### ISSUE TITLE
Could Bob be on Tiddlyhost?

### ISSUE THREAD

**Issue by twMat** [OokTech/TW5-Bob#186]
Dear @inmysocks , I'm posting here because there is no Discussion area. If it is not appropriately posted, obviously just close it or tell me to close it.

With Bob you've created the main piece in the puzzle for multi-user collaboration. The second main piece would be a public/semipublic server that hosts Bob and that people can conveniently use. An example of such a public server would be @simonbaird 's [Tiddlyhost](https://tiddlyhost.com/) (github [here](https://github.com/simonbaird/tiddlyhost)). Is there any direct reason, from Bob's perspective - or yours for that matter - why Bob should/could not be used on Tiddlyhost or comparable?

I'm posting the [mirrored question](https://github.com/simonbaird/tiddlyhost/issues/199) on Tiddlyhosts github.

Thank you.

**Comment by inmysocks** [comment]
If tiddlyhost works similarly to how tiddlyspot did Bob wouldn't work on it. Bob has a dedicated server component. Eventually I will get the secure server part finished in a way that is easy for other people to set up and then it could be a similar thing, but I don't think Bob will play well with tiddlyhost.

**Comment by twMat** [comment]
Aha, thanks Jed. I'll copy-paste your reply on the Tiddlyhost gh so Simon sees it.
Closing.
