### ISSUE TITLE
WebSocket Upgrade header string comparison is case sensitive and collides with apache reverse proxy mod_proxy_wstunnel

### ISSUE THREAD

**Issue by dunkla** [OokTech/TW5-Bob#187]
I don't know if pull requests are welcome, so here's the issue first:
Running tw5-bob worked out of the box. But running behind an apache2 reverse proxy, i always got the red alert box "WARNING: The connection to server hasn't been established yet.".
Turns out, `mod_proxy_wstunnel` sends the the Upgrade header in CamelCase (`WebSocket`). The upgrade handler in `commands/ws-server.js` does a literal string comparison `===` with `websocket`.

My fix:
```diff
diff --git a/commands/ws-server.js b/commands/ws-server.js
index 9bf1f27..fbc3576 100755
--- a/commands/ws-server.js
+++ b/commands/ws-server.js
@@ -306,7 +306,7 @@ if($tw.node) {
       }
     });
     httpServer.on('upgrade', function(request, socket, head) {
-      if(request.headers.upgrade === 'websocket') {
+      if(request.headers.upgrade.toLowerCase() === 'websocket') {
         if(request.url === '/') {
           $tw.wss.handleUpgrade(request, socket, head, function(ws) {
             $tw.wss.emit('connection', ws, request);

```

---

I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [ ] Windows
- [ ] OSX
- [x] Linux
- [ ] Other

and using

- [x] The nodejs version
- [ ] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [x] I am using the newest version
- [x] The answer to my question isn't listed in the documentation or this isn't
  a question
- [x] This is not a duplicate issue
- [x] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

**Comment by inmysocks** [comment]
Thank you!
Pull requests are very welcome, but I have been busy lately so I take a while to respond.
I will put this fix into the next release.
