### ISSUE TITLE
Can TW5-BOB be used straight from hosted on GitHub, with autosaving, from all devices?

### ISSUE THREAD

**Issue by UtopistList** [OokTech/TW5-Bob#188]
I have set up TW-BOB5 on Windows desktop and it works well, but how can I access it also from mobile (Android), the same instance, via the cloud (so that I don't need to keep my desktop with me or turned on)?

**Comment by inmysocks** [comment]
Bob can't run off of Github, it needs a server that can run node. I think that the simplest way to have Bob accessible from the internet is to have it installed on something like a digital ocean droplet with Nginx handling the authentication. I am working on making it easy to set up but I have been busy with other projects for a while.

**Comment by UtopistList** [comment]
Something maybe I don't fully understand in how it works.
The reason I thought it should work from GitHub because NodeJS doesn't
necessarily need to be installed, it's sufficient to have it unpacked it in
a folder to get TiddlyWiki run off of it, as portable.
That's why I thought that it should run from GitHub as portable, just like
it can run from a folder that is in Windows or Linux desktop, without
installing NodeJS on the OS.
Could you elaborate why it wouldn't work the same portable way as from a
folder in a desktop OS?
Thanks,
have a good night.
