### ISSUE TITLE
Are you planning new release?

### ISSUE THREAD

**Issue by ghost** [OokTech/TW5-Bob#190]
Just wanted to make sure, if you are planning to release any new updates?

**Comment by inmysocks** [comment]
yes, despite my lack of recent progress I haven't abandoned bob, but my day job has taken much more of my attention than I anticipated so it may be a while before anything significant happens.

**Comment by Kochise** [comment]
https://github.com/OokTech/TW5-Bob/issues/203#issuecomment-1782405301
