### ISSUE TITLE
Server breaks after http API request

### ISSUE THREAD

**Issue by MagicJF** [OokTech/TW5-Bob#202]
- [X] Linux
- [X] The nodejs version

I have a tiddler titled "oli" in a wiki named "AAA".
This get request works fine, returning the desired HTML, but the server breaks.

Here are the pictures:

![image](https://github.com/OokTech/TW5-Bob/assets/92638213/84d3b52a-ece9-4be0-add5-b6c654afb947)

![image](https://github.com/OokTech/TW5-Bob/assets/92638213/1bbbde9b-80aa-426c-baa7-ee73b43cd112)

Update:
I also found that pushing tiddlers does not work, it got stuck in a indefinitely waiting

![image](https://github.com/OokTech/TW5-Bob/assets/92638213/1b977178-f73b-451e-97b2-febd63bbabd9)

**Comment by inmysocks** [comment]
I haven't exaustively tested it but the recent updates should fix this error. If not let me know and I will reopen the issue.
