### ISSUE TITLE
Add support for single-file wikis

### ISSUE THREAD

**Issue by inmysocks** [OokTech/TW5-Bob#32]
The goal is to be able to list a single file wiki in the wikis list and it will be converted into a temporary node wiki which you can then edit the same as any other wiki and it will be exported as the single file wiki when you are done editing.

**Comment by hchaase** [comment]
+1
this would be great!!

**Comment by TiddlyTweeter** [comment]
I'm not so sure about this. I'm not against it. But I'm not convinced its so useful. Why would I want to edit a single file in Bob when I have access to multiple methods already that do that well?

What might be useful is a "converter" that will take a single file TW and copy it into a Bob version ".tid files" version and offer ability to save it as a Bob Wiki?

Just a thought.

**Comment by inmysocks** [comment]
This is closer to existing, but still not there yet. So far you can create a Bob wiki from a single file wiki and then export a Bob wiki to a single file wiki, which is the path that the finished version will take, but for now it is all manual.

**Comment by inmysocks** [comment]
The BobSaver addition adds a way to save single file wikis.
I could add some way for Bob to list the single file wikis also but I don't think that is necessary.

**Comment by TiddlyTweeter** [comment]
I agree. Tx.
