### ISSUE TITLE
Add a way to delete a wiki from the in-wiki interface.

### ISSUE THREAD

**Issue by inmysocks** [OokTech/TW5-Bob#33]
Just be very careful that it won't happen accidentally.

**Comment by TiddlyTweeter** [comment]
Just a comment, a thought, not support for the idea, or against it. 
       The one thing that stands out for me with Bob is you can get Bob to talk directly to the OS. I mean that is its brilliance. So, in my case, some of the "features" requested I don't need as I can myself develop them because Bob can do that. Hope this is clear and maybe relevant.

**Comment by inmysocks** [comment]
This is included
