### ISSUE TITLE
When renaming a tiddler on the file system the old version is sometimes left in the browser

### ISSUE THREAD

**Issue by inmysocks** [OokTech/TW5-Bob#35]
Make sure you read contributing.md and check the correct boxes below and then
add your issue text here.
If you don't than the issue will be tagged as spam and closed or deleted.

---

I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [ ] Windows
- [ ] OSX
- [x] Linux
- [ ] Other

and using

- [x] The nodejs version
- [x] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [x] I am using the newest version
- [x] The answer to my question isn't listed in the documentation or this isn't
  a question
- [x] This is not a duplicate issue
- [x] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

**Comment by tgirod** [comment]
This also happens when deleting a tiddler. To reproduce:

1. create a tiddler
2. delete it
3. the tiddler is deleted from the disk and the interface
4. reload the page
5. the deleted tiddler reappears

The only way I found to get rid of it is to restart the server.

**Comment by inmysocks** [comment]
It looks like this was fixed with #47
