### ISSUE TITLE
Make a setting in the settings.json to list paths for custom editions

### ISSUE THREAD

**Issue by inmysocks** [OokTech/TW5-Bob#39]
I think we can just append it to the TIDDLYWIKI_EDITIONS_PATH environment variable.

**Comment by TiddlyTweeter** [comment]
The only problem with environment variables is I don't think its so easy to make them portable? I don't know enough technically to be sure, but given Bob has become very good at portability I just wanted to ensure that won't break it. Personally, a path relative to the install would be fine.

**Comment by inmysocks** [comment]
This is added in 1.0.2
