### ISSUE TITLE
Add an auto backup option

### ISSUE THREAD

**Issue by inmysocks** [OokTech/TW5-Bob#41]
This may be better as a separate plugin.

The buildHTMLWiki message would make this relatively simple. I think that we could have it save a single file wiki version after some length of time as long as there are edits newer than the previous backup version.

Things to include:
- Rolling backups, keep only the newest x versions
- Configurable backup location(s) (all wikis in one place, each wikis gets its own folder, etc)

Alternately we could set it up so that it saves an archive of the tiddlers folder. That may introduce more external dependencies.

**Comment by TiddlyTweeter** [comment]
Just FYI, I prefer to use normal backup programs. I find them a better solution for me. 

Though I have nothing against it I'd prefer you kept it as an extra, a plugin.

**Comment by hchaase** [comment]
+1

**Comment by inmysocks** [comment]
This is added in the next version.
