### ISSUE TITLE
Unclear reference to address on 'Hello!' tiddler

### ISSUE THREAD

**Issue by aormond** [OokTech/TW5-Bob#49]
On the 'Hello!' tiddler, it says "After setting the host and restarting you can connect to this wiki from another computer on the same network by entering the above into the address bar of a browser." However, there the address is not "above". I assume it's referring to the ip address and port that is at the top of the 'Readme' tiddler. It's a little confusing for a new user. Thanks!

---

I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [x] Windows
- [ ] OSX
- [ ] Linux
- [ ] Other

and using

- [ ] The nodejs version
- [x] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [x] I am using the newest version
- [x] The answer to my question isn't listed in the documentation or this isn't
  a question
- [x] This is not a duplicate issue
- [x] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

**Comment by inmysocks** [comment]
Thank you for pointing that out. I am hopefully going to be releasing 1.0.3 soon and it has a lot of updates. I will add this to the list of things to change for the release.

**Comment by inmysocks** [comment]
Hopefully it is more clear now. Let me know if there are more problems
