### ISSUE TITLE
Wiki folder Lost to Bob

### ISSUE THREAD

**Issue by AnthonyMuscio** [OokTech/TW5-Bob#60]
I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [X] Windows
- [ ] OSX
- [ ] Linux
- [ ] Other

and using

- [ ] The nodejs version
- [X] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [X] I am using the newest version (I think so, not sure how to check)
- [X] The answer to my question isn't listed in the documentation or this isn't
  a question
- [X] This is not a duplicate issue
- [X] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

Running the Single File Executable on Windows 10 has being working well. I recently installed the plugin for revisions http://j.d.revisions.tiddlyspot.com/ as discussed here but not tested https://groups.google.com/forum/?hl=en#!topic/tiddlywiki/EZhMkt0BDn0

Unfortunately the Wiki would not reload in Bob, I deleted the new plugin tiddler

I had backups and tried a few things. But can no longer get it to open in Bob, Although I have managed to load it via TiddlyServer/NodeJS

The Folder wiki no longer has the Bob Settings and the link from the wiki listing in bob remains.

Is it simply a matter of installing the bob plugin or something else to make the folder wiki accessible in Bob again, as it was originally made from Bob?

Or could/should I create a new wiki and import tiddlers from a single file backup version?

Thanks in Advance
Tony

**Comment by AnthonyMuscio** [comment]
I installed the latest SingleFile Version to be sure.

**Comment by inmysocks** [comment]
@AnthonyMuscio did this get resolved?

**Comment by inmysocks** [comment]
Without more information I can't do anything here and there has been no response so I am closing the issue.
