### ISSUE TITLE
Request: "Editions List" be configurable to hide editions the user will never make Wiki from. 

### ISSUE THREAD

**Issue by TiddlyTweeter** [OokTech/TW5-Bob#63]
Its fantastic that you can make a wiki of any standard edition, plus any personal edition via the editionsPath.

I'm hitting an "overwhelm" issue in that I'm being shown options for editions I would never use, and others I'd only use once in a blue moon.

Could the list be configurable so you only see what you really use? Or, I don't mind manually editing a list if its straightforward to do so. I'd just need documentation to be sure I didn't mess Bob up.

---

I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [x] Windows
- [ ] OSX
- [ ] Linux
- [ ] Other

and using

- [ ] The nodejs version
- [x] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [x] I am using the newest version
- [x] The answer to my question isn't listed in the documentation or this isn't
  a question
- [x] This is not a duplicate issue
- [x] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

**Comment by inmysocks** [comment]
This has been added, you can make a list of editions you want visible by creating a tiddler called $:/ListedEditions and putting the names of the editions in the text field. This is now documented in the Creating New Wikis part of the documentation. Let me know if you have further problems.
