### ISSUE TITLE
Issue: internalFetch fails on sub-wiki

### ISSUE THREAD

**Issue by TiddlyTweeter** [OokTech/TW5-Bob#65]
BobEXE 1.1.0 on Windows 7 in Firefox 52. 64-bit.

This internalFetch works as expected ...
```
<$button>
 TEST fetch "get" tiddler from ''silvia''
  <$action-websocketmessage
    $type='internalFetch'
    fromWiki='silvia'
    filter='[[get]]'
    transformFilter=''
  />
</$button>
```

This internalFetch from a sub-wiki (otherwise working fine) fails ...
```
<$button>
  fetch ''cool mint'' palette
  <$action-websocketmessage
    $type='internalFetch'
    fromWiki='lib/bits/palettes'
    filter='[[$:/jd/palette/CoolMint]]'
    transformFilter=''
  />
</$button>
```

----

- [x] Windows
- [ ] OSX
- [ ] Linux
- [ ] Other

and using

- [ ] The nodejs version
- [x] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [x] I am using the newest version
- [x] The answer to my question isn't listed in the documentation or this isn't
  a question
- [x] This is not a duplicate issue
- [x] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

**Comment by inmysocks** [comment]
This should be fixed in version 1.2.2, let me know if it continues after I make the release.
