### ISSUE TITLE
Bob locks shadow tiddlers when editing them is cancelled.

### ISSUE THREAD

**Issue by mklauber** [OokTech/TW5-Bob#67]
I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [ ] Windows
- [ ] OSX
- [x] Linux
- [ ] Other

and using

- [ ] The nodejs version
- [x] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [x] I am using the newest version
- [x] The answer to my question isn't listed in the documentation or this isn't
  a question

- [x] This is not a duplicate issue
- [x] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

---

When using the the single file executable on 64 bit linux (and possibly other systems), opening a shadow tiddler, clicking the edit button, but cancelling the "Are you sure" dialog results in the edit button being replaced with a padlock symbol, and being unable to edit that tiddler until the page is reloaded.  

Example:  ![image](https://user-images.githubusercontent.com/563721/47384115-32e3c980-d6d4-11e8-81a3-69f0d0080230.png)

**Comment by inmysocks** [comment]
I think that this issue was fixed in version 1.2.0, there are some other errors in that version so I will be releasing 1.2.1 later today. I saw this before and now I don't so when you have a chance please test this with the 1.2.1 version and see if it is still a problem for you.

**Comment by mklauber** [comment]
I can confirm that the issue appears to be fixed in version 1.2..0
