### ISSUE TITLE
Could also be collaborated online?

### ISSUE THREAD

**Issue by gesundelehre** [OokTech/TW5-Bob#70]
Is there a possibility to use this software set-up somehow on a server to distribute tiddlywikis remotely where multiple people could work on the same wiki and it would update almost immediately on everyones local copy?

If it would be possible, how can my idea be achieved?

Looking forward to your reply.

Sincerely,
gesundelehre

**Comment by PaulReiber** [comment]
While that could certainly be achieved with the right amount of effort/work/new-code, it's definitely not something that'd be any easier with "bob" as opposed to building it yourself.

Every "local" tiddlywiki would need to either directly, or via a cenralized service, send updates to every OTHER copy of itself, everywhere else in existence, semi-atomically, when one hits "save" on a tiddler.

That is not what bob does.  Bob implements multi-user server-side TW.  Not local-file-based TW.

**Comment by gesundelehre** [comment]
So would it be possible then to run Bob on a server (e.g. free linux Web Host) instead of on the own computer?

**Comment by inmysocks** [comment]
Yes, the wikis at ooktech.xyz use Bob and the server side code that has the login and access control available here https://github.com/OokTech/SecureWikiServer

I don't know of anyone other than me who has run a server for it, so I don't know what is missing from the documentation.

As Paul said, Bob lets multiple people connect to the same server and use the same wiki that way, it doesn't sync files between computers. There are some plans for syncing between the server components, but there hasn't been any significant progress on that.

**Comment by gesundelehre** [comment]
Did i understand that correctly, that collaboration as such is not possible just like with Bob in a local network?

**Comment by gesundelehre** [comment]
Did i understand that correctly, that thus collaboration over the internet on a tiddlywiki is not possible like collaboration with Bob in a local network?

**Comment by inmysocks** [comment]
It is possible, the link I sent you was the server that I use to do it. It works fine over the internet.

**Comment by gesundelehre** [comment]
What are the Server-Requirements to get this running? 

Concerning the Documentation, it would greatly help if you would provide a Todo-List with a Ordered/Numbered List of Steps to take starting from a Clean Webserver - a Todo-List showing what steps needs to be done and thought about and in which order.

That would at least help me much to install the Server-Application.

If you could provide such a structure to the Documentation, that would be awesome.

**Comment by inmysocks** [comment]
If the server can run the node than it should have no trouble running this.

I will update documentation as I can. If you have specific questions ask them in the other repo, for now I am closing this issue.
