### ISSUE TITLE
add lazy loading option

### ISSUE THREAD

**Issue by cedardocster** [OokTech/TW5-Bob#72]
Feature Request:

I have a TW with loads of tiddlers (over 3000) and (especially on Android) it takes quite a while to initially load.  Lazy loading would (I think speed this up quite a bit)

---

I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [ ] Windows
- [ ] OSX
- [x ] Linux
- [ ] Other

and using

- [ ] The nodejs version
- [x ] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [x ] I am using the newest version
- [x ] The answer to my question isn't listed in the documentation or this isn't
  a question
- [ x] This is not a duplicate issue
- [x ] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

**Comment by inmysocks** [comment]
This is not a bad idea but I think that it is going to be low priority.

As a stop-gap until it is implemented you may be able to take advantage of the new features that let you create separate wikis from tiddlers in your existing wiki to split it up by subject area and let you have multiple smaller wikis that load faster.

**Comment by BillDStrong** [comment]
Actually, i don't know how feasible this is, but couldn't you reuse the features form the create seperate wikis feature and essentially only publish to the user a wiki that contains the tiddlers they have requested? Still provide the metadata necessary to do the built-in searches? may not be worth it, depending on the average size of the tiddlers, I guess.

**Comment by inmysocks** [comment]
That is possible now, the problem with that in.this situation is that there isn't cuerrently a mechanism for letting the server know which tiddlers you want without making a new wiki. I think that even if this solves the op I will make a new issue for this.

**Comment by inmysocks** [comment]
Lazy loading is implemented in the newest release.
