### ISSUE TITLE
Alternative File Extension for TiddlyWiki Files

### ISSUE THREAD

**Issue by AnthonyMuscio** [OokTech/TW5-Bob#75]
Jed,

Please consider my suggestion here for Bob [Alternative File Extension for TiddlyWiki Files #3719](https://github.com/Jermolene/TiddlyWiki5/issues/3719)

Apart for the key points raised in that issue I believe it would be an advantage for users to be able to have single file wikis that open in Bob and and be exported by Bob if they have the alternate file extension.

I believe this could be fairly trivial extension.

As Bobexe is an installable application this would also be an opportunity to provide the ability to associate tw files with the browser and or the browser of choice, perhaps even a co-install of the desktop side Timimi and browser add on, as these further help enable Bob to work with Single File Wikis and not miss out on handling the easy to email .tw files proposed.

There is no hurry but just a desire to extend the definition of a valid tiddlywiki to .tw files to extend its usability, transfer-ability and ease of use.

I can provide the necessary Registry changes for Windows.

Regards
Tony
---

I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [X] Windows
- [X] OSX
- [x] Linux
- [] Other

and using

- [X] The nodejs version ???
- [X] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [X] I am using the newest version
- [X] The answer to my question isn't listed in the documentation or this isn't
  a question
- [X] This is not a duplicate issue **except I am asking this of Timimi, TiddlyDesktop, TiddlyWiki core, TiddlyServer etc...**
- [X] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

**Comment by inmysocks** [comment]
I will look into this, it should be very simple to do this. It would be a simple toggle in the control panel to change the extension of the saved file.

**Comment by inmysocks** [comment]
The action-download wiki widget lets you set the default name for downloads, so you can use that to give whatever extension you want.
