### ISSUE TITLE
Using the FileSystemPaths system tiddler breaks 'Save Plugin As Folder'

### ISSUE THREAD

**Issue by joshuafontany** [OokTech/TW5-Bob#80]
Hi :)

I've noticed that when I set the options in [$:/config/FileSystemPaths.tid](https://tiddlywiki.com/#Customising%20Tiddler%20File%20Naming) that the 'Save Plugin As Folder' breaks. I get errors such as this:

`{ Error: ENOENT: no such file or directory, open 'c:\joshuafontany\TiddlyWiki5\plugins\matabele\action-maketid\_system\plugins\matabele\widgets\action-maketid.js.tid'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'c:\\joshuafontany\\TiddlyWiki5\\plugins\\matabele\\action-maketid\\_system\\plugins\\matabele\\widgets\\action-maketid.js.tid' }`

When I test in a wiki without the FileSystemPaths tiddler set, it works fine. This may be because some tiddlers in one of my test plugins contain sub-tiddlers that are not in the normal $:/plugins/name/pluginName/ namespace.

---

I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [X] Windows
- [ ] OSX
- [ ] Linux
- [ ] Other

and using

- [X] The nodejs version
- [ ] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [X] I am using the newest version
- [X] The answer to my question isn't listed in the documentation or this isn't
  a question
- [X] This is not a duplicate issue
- [X] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

**Comment by inmysocks** [comment]
I have removed the save plugin as a folder option in the control panel for now. There are too many errors associated with it. I am keeping this open so I know to test for it when I get around to trying to fix it.

**Comment by joshuafontany** [comment]
I am not able to reproduce this after patching my JsonMangler plugin, which was mutating base classes in a sub-library (whoops).

I was able to successfully unpack TheDiveO/FontAwesome.

**Comment by inmysocks** [comment]
Ok, I will close this for now. I am still not comfortable with the save plugin as folder functionality so in the next release the button will be removed. Everything will still be available but people will have to add their own button to avoid more problems until I can make the experience smoother.
