### ISSUE TITLE
While using custom FileSystemPaths some Bob system tiddlers are saved in the wrong path

### ISSUE THREAD

**Issue by mauloop** [OokTech/TW5-Bob#83]
I use a custom $:/config/FileSystemPaths, with this content:

[removeprefix[$:/_mau/]addprefix[_mau/]]
[removeprefix[$:/]addprefix[system/]]
[!prefix[$:/]addprefix[user/]]

While updating the plugin list in ControlPanel/BobSettings/ManagePlugins, the $:/Bob/AvailablePluginList tiddler is saved as:

tiddlers\system\Bob\system\Bob\AvailablePluginList.tid

which  is not what I expected, given the settings in FileSystemPaths (system\bob is repeated, nested in system\bob !!!). The same happened with $:/Bob/AvailableThemeList.

This are the only occurences of this case. I tried to create other system tiddlers ($:/_mau/something or $:/Bob/dummy) and they have been saved in the expected path.

I didn't notice any side effects that could be related to this behaviour. Apparently it has no  practical consequences. I just wanted to inform you so you can eventually investigate it further.

Verified with Bob 1.2.1 and Bob 1.2.2rc5.

---

I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [x] Windows
- [ ] OSX
- [ ] Linux
- [ ] Other

and using

- [ ] The nodejs version
- [x] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [x] I am using the newest version
- [x] The answer to my question isn't listed in the documentation or this isn't
  a question
- [x] This is not a duplicate issue
- [x] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

**Comment by joshuafontany** [comment]
I have also seen this recursive nesting when you have the $:/config/FileSystemPaths tiddler set. But only with tiddlers in the $:/ "__system" path, so I think it has something to do with saving shadow-tiddlers that get edited (?).

**Comment by inmysocks** [comment]
I just pushed changes to the plugin version that may fix this problem but I am not certain because I never found a method of reliably replicating it.

I need to do more testing before I make a new BobEXE release, so that may be a while.

**Comment by inmysocks** [comment]
I believe this is fixed now so I am closing the issue, if the problem continues let me know and I will reopen it.
