### ISSUE TITLE
Subwiki name dose not support unicode.

### ISSUE THREAD

**Issue by peter58228** [OokTech/TW5-Bob#85]
I am running windows version TW5-BobEXE. 
Subwiki can't be opened if wiki name is unicode (in my case, Chinese). The link of sub wiki can be create, but page  cannot open.
---

I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [ x] Windows
- [ ] OSX
- [ ] Linux
- [ ] Other

and using

- [ ] The nodejs version
- [x] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [x] I am using the newest version
- [ ] The answer to my question isn't listed in the documentation or this isn't
  a question
- [x] This is not a duplicate issue
- [ ] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

**Comment by inmysocks** [comment]
I believe I have found the problem. It looks like many non-europeans characters are outside the characters used in utf-8 and some javascript functions do not handle them correctly. I am looking up solutions.

Thank you for letting me know about this, it is interesting and not something I would have found by myself.

**Comment by inmysocks** [comment]
I think I fixed the bug. The fixed version is uploaded here https://github.com/OokTech/TW5-BobEXE/releases/tag/1.2.2r6

It has worked on my tests, please let me know if solves the problem for you.

**Comment by peter58228** [comment]
Chinese subwiki name now working fine in **new wiki folder** (create a new folder, put BobWin.exe inside and run),.

Two problems if I update BobWin.exe to an existing wiki folder.

1. After create a subwiki with Chinese characters,  the name in subwiki list different with what I create. For example: to this: 
Create subwiki: `中文測試` , The link in subwiki list: `中文測試/__path` , Folder name: `中文測試`
Create subwiki: `Hello 中文測試` , The link in subwiki list:  `[[Hello 中文測試/]]__path` , Folder name: `Hello 中文測試`

2. New function: `Available Wikis:  <>List in sidebar [Update List]` not show.

**Comment by inmysocks** [comment]
In the wiki that is showing problems please check if you have a tiddler called $:/plugins/OokTech/Bob/Wiki Listing, if you do delete it. This will remove the listing from the sidebar but you will be able to re-add it from the control panel.

If that does not work I will look into this further.

**Comment by peter58228** [comment]
After simplifying my test environment, I confirmed that this is not a proxy issue.

After delete '$__plugins_OokTech_Bob_Wiki Listing.tid' from all subwiki folder. XXX/__path no longer appears.

Thanks again.

**Comment by inmysocks** [comment]
Are you still having any trouble? If not I will close this issue.
