### ISSUE TITLE
fails after reset server 

### ISSUE THREAD

**Issue by Valdus92** [OokTech/TW5-Bob#94]
Here is what I'm doing and tell me how to do it right. 

I hit boxexe, get wiki
I change ws server host to 0.0.0.0. 
I hit update settings and hit save 
I reset the server (by hitting reload?)
I get ERR_CONNECTION_RESET over and over and over. 
What am I doing (wrong)?

---

I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [X ] Windows
- [ ] OSX
- [ ] Linux
- [ ] Other

and using

- [ ] The nodejs version
- [X ] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [ ] I am using the newest version
- [X ] The answer to my question isn't listed in the documentation or this isn't
  a question
- [ X] This is not a duplicate issue
- [ ] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

**Comment by inmysocks** [comment]
You have to change the setting, save it then go into the control panel -> Bob Settings -> Server and click on the `Shutdown Wiki` button, then reopen BobEXE.
After that it should work correctly.
