### ISSUE TITLE
Crash on Windows when deleting an empty directoy

### ISSUE THREAD

**Issue by joshuafontany** [OokTech/TW5-Bob#97]
Obscure node.js issue with the filesystem watcher on Windows only.

Recreate it by using the config tiddler below, then create a tiddler named "Test/Tiddler 1". Then re-name the tiddler to "Tiddler 1". Behind the scenes, Bob deletes the old tiddler, creates the new (renamed) tiddler, and if the directory left behind is empty tries to delete it somewhere in the middle of those 2 operations.

If the Test folder is empty after the rename, Bob will crash when the empty directory gets called in the 'unlink' function. As this occurs before the new (renamed) tiddler is written, the tiddler is effectively deleted via bash/command line (no recovery aside from disk forensics).

I have tracked down a work-around that silences the error and returns control flow back to the server, and it seems to work fine after testing a few iterations of the issue.

```
title: $:/config/FileSystemPaths
type: text/vnd.tiddlywiki

[is[system]removeprefix[$:/]addprefix[_system/]]
[tag[task]addprefix[mytasks/]]
[!has[draft.of]]
```

---

I am running (check any that apply, put an x inside the [ ] to check a box, like this: [x]):

- [x ] Windows
- [ ] OSX
- [ ] Linux
- [ ] Other

and using

- [x ] The nodejs version
- [ ] The single file executable

Before posting I read [issue guidelines](./IssueGuidelines.md) and:

- [x ] I am using the newest version
- [x ] The answer to my question isn't listed in the documentation or this isn't
  a question
- [x ] This is not a duplicate issue
- [x ] I have not done anything that required me to set acceptance to
  `I Will Not Get Tech Support For This`

**Comment by inmysocks** [comment]
I believe this is fixed now, I need to test more before closing the issue.

**Comment by inmysocks** [comment]
This should be fixed, let me know if you run into it in the next version. It should be released later today.
